{{- if .Values.gitlab.postgresql.install -}}
{{- if .Values.gitlab.postgresql.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "zh-gitlab-postgresql"
spec:
  accessModes:
    - {{ .Values.gitlab.postgresql.persistence.accessMode | quote }}
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.gitlab.postgresql.persistence.size }}
  storageClassName: {{ .Values.gitlab.postgresql.persistence.storageClass }}

  {{ if .Values.gitlab.postgresql.persistence.volumeName }}
  volumeName:
  {{ toYaml .Values.gitlab.postgresql.persistence.volumeName | indent 4 }}
  {{- end -}}

  selector:
  {{- if .Values.gitlab.postgresql.persistence.matchLabels }}
    matchLabels:
{{ toYaml .Values.gitlab.postgresql.persistence.matchLabels | indent 6 }}
  {{- end -}}
{{- end -}}
{{- end -}}
