{{- if .Values.gitlab.prometheus.install -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "zh-gitlab-gitlab-prometheus"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: {{ .Values.gitlab.prometheus.server.persistentVolume.storageClass }}
  {{- if .Values.gitlab.prometheus.server.persistentVolume.matchLabels }}
  matchLabels:
{{ toYaml .Values.gitlab.prometheus.server.persistentVolume.matchLabels | indent 4 }}
  {{- end -}}
{{- end -}}
